server {
    listen 80;
    root /var/www/example.com/html;
    index index.html index.html;
    alo lol;

    try_files $uri $uri/ =403;
}

server {
    listen 550;
    root /var/www/example.com/html;
    index index.html index.html;
    location / {
        index index.html index.html;
    }
    location /images {
      try_files $uri $uri/ =401;
    }
    try_files $uri $uri/ =403;
}


server {
    listen 820;
    root /var/www/example.com/html;
    index index.html index.html;

    location /images {
     dfggddg dfggd;
    }
}
