server
{
    listen 9000;
    host 127.0.0.1;
    server_name server1;
    error_page 404 error_pages/404.html;
    # max_body_size 3000000;
    location / {
        root www/;
        index index.html;
        autoindex off;
    }
    location /home {
        root www/;
        index 200.html;
        cgi_enable on;
        upload_enable on;
    }
    location /favicon.ico
    {
        root www/;
        index ultrakill.png;
    }
    location /main
    {
        root www/;
        index main.cpp;
    }
    location /upload {
        index meow.html;
        root www/;
        cgi_enable off;
        upload_enable on;
    }
}


